# Netlify configuration for whimsical-licorice-fa2bd7
# Project: still testing CitizenScientistMiniApp copy 2
# Email: efop77392@gmail.com
# Site ID: cff17aec-4e8d-4600-a7fa-93dc30f0da69

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
