services:
  - type: web
    name: citiscience-backend
    env: node
    plan: free
    buildCommand: cd src/mongo-api && npm install
    startCommand: cd src/mongo-api && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: DB_NAME
        value: citiscience
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - src/mongo-api/**
        - package.json
        - package-lock.json 